package com.opensource.techblog.sampleservice.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Teacher service. Represents a row in the &quot;sample_sb_Teacher&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.opensource.techblog.sampleservice.model.impl.TeacherModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.opensource.techblog.sampleservice.model.impl.TeacherImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Teacher
 * @see com.opensource.techblog.sampleservice.model.impl.TeacherImpl
 * @see com.opensource.techblog.sampleservice.model.impl.TeacherModelImpl
 * @generated
 */
public interface TeacherModel extends BaseModel<Teacher> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a teacher model instance should use the {@link Teacher} interface instead.
     */

    /**
     * Returns the primary key of this teacher.
     *
     * @return the primary key of this teacher
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this teacher.
     *
     * @param primaryKey the primary key of this teacher
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the teacher ID of this teacher.
     *
     * @return the teacher ID of this teacher
     */
    public long getTeacherId();

    /**
     * Sets the teacher ID of this teacher.
     *
     * @param teacherId the teacher ID of this teacher
     */
    public void setTeacherId(long teacherId);

    /**
     * Returns the teacher name of this teacher.
     *
     * @return the teacher name of this teacher
     */
    public long getTeacherName();

    /**
     * Sets the teacher name of this teacher.
     *
     * @param teacherName the teacher name of this teacher
     */
    public void setTeacherName(long teacherName);

    /**
     * Returns the dob of this teacher.
     *
     * @return the dob of this teacher
     */
    public long getDob();

    /**
     * Sets the dob of this teacher.
     *
     * @param dob the dob of this teacher
     */
    public void setDob(long dob);

    /**
     * Returns the subject of this teacher.
     *
     * @return the subject of this teacher
     */
    public long getSubject();

    /**
     * Sets the subject of this teacher.
     *
     * @param subject the subject of this teacher
     */
    public void setSubject(long subject);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        com.opensource.techblog.sampleservice.model.Teacher teacher);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.opensource.techblog.sampleservice.model.Teacher> toCacheModel();

    @Override
    public com.opensource.techblog.sampleservice.model.Teacher toEscapedModel();

    @Override
    public com.opensource.techblog.sampleservice.model.Teacher toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
