package com.opensource.techblog.sampleservice.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.opensource.techblog.sampleservice.model.Teacher;
import com.opensource.techblog.sampleservice.service.TeacherLocalServiceUtil;

/**
 * The extended model base implementation for the Teacher service. Represents a row in the &quot;sample_sb_Teacher&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TeacherImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TeacherImpl
 * @see com.opensource.techblog.sampleservice.model.Teacher
 * @generated
 */
public abstract class TeacherBaseImpl extends TeacherModelImpl
    implements Teacher {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a teacher model instance should use the {@link Teacher} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            TeacherLocalServiceUtil.addTeacher(this);
        } else {
            TeacherLocalServiceUtil.updateTeacher(this);
        }
    }
}
